---
- name: Enable EAP repository
  shell: subscription-manager repos --enable="{{ eap_rpm_repository }}"

#- name: Install EAP
#  yum: name=@{{ item }} state=latest
#  with_items: "{{ eap_package }}"

- name: Install EAP 
  shell: yum groupinstall -y "{{ eap_package }}"

- service:
    name: "{{ eap_service_name_prefix }}{{ eap_operating_mode }}"
    enabled: yes

- service:
    name: "{{ eap_service_name_prefix }}{{ eap_operating_mode }}"
    state: started
